---
ID: "7d18684c-7b1f-4f6c-8057-9a13d0902aed"
Parent: "80250061-fbc6-4253-9273-528d1706d4e4"
Template: "80250061-fbc6-4253-9273-528d1706d4e4"
Path: /sitecore/templates/Project/ESDemo/Components/Hero/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240104T195526Z
    - ID: "4c37debb-adbe-430d-a7e3-269b5613a72e"
      Hint: heroBody
      Value: Body
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "db4d7782-4edb-4e9e-8760-2c7c8c33a538"
    - ID: "b2c1b074-0138-457e-a73d-dedabf6b61d2"
      Hint: heroHeading
      Value: Heading
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240104T195557Z
