---
ID: "afa0faa3-49b0-4cf6-b8c1-ea92dae391aa"
Parent: "fe7a9111-1cea-4ea0-8a7a-4fa27bce0a66"
Template: "fe7a9111-1cea-4ea0-8a7a-4fa27bce0a66"
Path: /sitecore/templates/Project/ESDemo/LIT/Rendering Parameters/LIT Component Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240105T213315Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6b55c33b-994b-4e29-947d-b40e7163b755"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240109T174336Z
